### ISSUE TITLE
抓包无法进入我在校园小程序

### ISSUE THREAD

**Issue by Createrliu** [jimlee2002/Actions-WoZaiXiaoYuanPuncher#18]
小程序报错

Could not load the requested resource.
Error code: -202 (net::ERR_CERT_AUTHORITY_INVALID)

**Comment by jimlee2002** [comment]
抓包软件没配置好https证书，请自行百度

**Comment by Createrliu** [comment]
已解决，感谢回复



Jim Lee ***@***.***> 于 2021年12月20日周一 下午6:14写道：

**Comment by Createrliu** [comment]
老哥你好，我有个问题，一日三检和健康打卡的选项标志都是anwers，在environment secrets里是如何区分的

刘不易 ***@***.***> 于 2021年12月20日周一 下午9:01写道：
