### ISSUE TITLE
事件触发器设置了但是没有在规定时间运行怎么办

### ISSUE THREAD

**Issue by hahjiang** [jimlee2002/Actions-WoZaiXiaoYuanPuncher#20]
到点了不会自动运行 不知道怎么回事

**Comment by jimlee2002** [comment]
看你的脚本，运行是没问题的。
关于定时，有两个需要注意的地方：
1. Github Action服务器使用的时间是UTC，转换为北京时间（UTC+8）需要换算。
2. 由于计划任务需要排队，Github Action并不会准时执行脚本，实测会延迟1h左右。
