### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by John147159123** [jimlee2002/Actions-WoZaiXiaoYuanPuncher#26]
可以留一个联系方式吗

**Comment by jimlee2002** [comment]
有任何问题请直接在issue上描述，不接受私下交流，抱歉。

**Comment by jimlee2002** [comment]
也请您不要在我的博客留言板中留下无关内容或骚扰他人，谢谢合作。

**Comment by John147159123** [comment]
sorry，刚看到邮件，实在是不好意思，已 在issue描述了

Jim Lee ***@***.***> 于2022年1月20日周四 13:24写道：
