### ISSUE TITLE
健康打卡出错：{'code': 500, 'message': '服务出错(500)'}

### ISSUE THREAD

**Issue by John147159123** [jimlee2002/Actions-WoZaiXiaoYuanPuncher#27]
配置都正确，还是出现了错误
正在打卡...
{'code': 500, 'message': '服务出错(500)'}
打卡失败

**Comment by jimlee2002** [comment]
嗯？非常奇怪，第一次见到这样的错误……
可能是secrect里填的东西格式不对？试着重新填一遍secrect？

**Comment by jimlee2002** [comment]
这边看到你打的是每天一次的健康打卡，猜测是健康打卡传递的问题回答参数不对
可以提供下你这边我在校园小程序上健康打卡界面的截图吗？

**Comment by John147159123** [comment]
> 这边看到你打的是每天一次的健康打卡，猜测是健康打卡传递的问题回答参数不对 可以提供下你这边我在校园小程序上健康打卡界面的截图吗？
![Screenshot_20220123_163440 jpg](https://user-images.githubusercontent.com/91882904/150670800-f190973d-9223-4926-86c7-594e7ff7e4ce.jpg)

**Comment by jimlee2002** [comment]
了解了，是不同学校健康打卡所需打卡参数不同导致的问题。
这边还请你参考仓库首页的文档最后的介绍，手动抓一下小程序打“健康打卡”项目时的网络封包，并参考介绍中的图片，将抓包的数据**打码地理位置信息和其他个人信息**后截图发一下，我会协助你修改脚本的相关参数。

**Comment by John147159123** [comment]
> 了解了，是不同学校“健康打卡”回答问题不同、所需打卡参数不同而导致的问题。 这边还请你参考仓库首页的文档最后的介绍，手动抓一下小程序打“健康打卡”项目时发送的网络封包，并参考介绍中的图片，将抓到的数据**打码地理位置信息和其他个人信息**后截图发一下，我会协助你修改脚本的相关参数。

![image](https://user-images.githubusercontent.com/91882904/150671214-fdb3b0c5-eabe-4efc-8a30-722b73a2fd0b.png)

**Comment by jimlee2002** [comment]
> > 了解了，是不同学校“健康打卡”回答问题不同、所需打卡参数不同而导致的问题。 这边还请你参考仓库首页的文档最后的介绍，手动抓一下小程序打“健康打卡”项目时发送的网络封包，并参考介绍中的图片，将抓到的数据**打码地理位置信息和其他个人信息**后截图发一下，我会协助你修改脚本的相关参数。
> 
> ![image](https://user-images.githubusercontent.com/91882904/150671214-fdb3b0c5-eabe-4efc-8a30-722b73a2fd0b.png)

**Comment by jimlee2002** [comment]
> > 了解了，是不同学校“健康打卡”回答问题不同、所需打卡参数不同而导致的问题。 这边还请你参考仓库首页的文档最后的介绍，手动抓一下小程序打“健康打卡”项目时发送的网络封包，并参考介绍中的图片，将抓到的数据**打码地理位置信息和其他个人信息**后截图发一下，我会协助你修改脚本的相关参数。
> 
> ![image](https://user-images.githubusercontent.com/91882904/150671214-fdb3b0c5-eabe-4efc-8a30-722b73a2fd0b.png)

（为避免个人信息泄露，最好给图片中的地理位置信息打个码）

**Comment by John147159123** [comment]
> > > 了解了，是不同学校“健康打卡”回答问题不同、所需打卡参数不同而导致的问题。 这边还请你参考仓库首页的文档最后的介绍，手动抓一下小程序打“健康打卡”项目时发送的网络封包，并参考介绍中的图片，将抓到的数据**打码地理位置信息和其他个人信息**后截图发一下，我会协助你修改脚本的相关参数。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/91882904/150671214-fdb3b0c5-eabe-4efc-8a30-722b73a2fd0b.png)
> 
> （为避免个人信息泄露，最好给图片中的地理位置信息打个码）

好的谢谢
![111111](https://user-images.githubusercontent.com/91882904/150671427-d344f036-75ed-4474-bd34-c751a8ae51bb.png)

**Comment by jimlee2002** [comment]
了解。
稍后我会更新脚本，支持通过新建Secrect `ANSWER` 来自定义问题的回答，所需填写的值为封包中answers字段所对应的value。
![20220123_DTBQ3CkDab](https://user-images.githubusercontent.com/21117946/150672214-50fc9dd5-d1ee-4983-883f-5b44cb9b270e.png)
该Secrect为可选，不新建则将传递默认参数。
请稍等，脚本更新后我会在本issue通知你。

**Comment by John147159123** [comment]
> 了解。 为适应不同学校打卡项目与所需参数可能存在的不同，稍后我会更新脚本，支持通过新建Secrect `ANSWER` 来自定义问题的回答，所需填写的值为封包中answers字段所对应的value。 ![20220123_DTBQ3CkDab](https://user-images.githubusercontent.com/21117946/150672214-50fc9dd5-d1ee-4983-883f-5b44cb9b270e.png) 该Secrect为可选，不新建则将传递默认参数。 请稍等，脚本更新后我会在本issue通知你。

好的，谢谢大哥

**Comment by BlueSky0329** [comment]
哥 能给个联系方式不

**Comment by jimlee2002** [comment]
> 哥 能给个联系方式不

不接受任何私下交流，有任何问题请直接发issue，谢谢。

**Comment by jimlee2002** [comment]
已更新，请参考最新的文档新建Secrect`ANSWERS`试试看。

**Comment by jimlee2002** [comment]
看你的运行日志似乎没问题了？如果问题解决了的话就close掉这个issue吧。

**Comment by jimlee2002** [comment]
先关掉这条issue了，有问题reopen。
