### ISSUE TITLE
github的ip段是多少 钉钉一直收不到推送

### ISSUE THREAD

**Issue by BlueSky0329** [jimlee2002/Actions-WoZaiXiaoYuanPuncher#29]

**Comment by jimlee2002** [comment]
看了下你的日志，发现钉钉机器人无法正确输出推送失败的相关错误信息。
已修复该问题，请重新fetch一下代码，以便确认钉钉机器人推送失败的原因。

**Comment by jimlee2002** [comment]
关于 Github Actions runners 的地址段，请参考官方指南：[About GitHub-hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#ip-addresses)

**Comment by BlueSky0329** [comment]
感谢大哥 可是我又遇到了脚本没有定时触发的问题 我才cron表达式里把每个时间段都加上了 可是都没有定时触发 该怎么解决

**Comment by jimlee2002** [comment]
> 感谢大哥 可是我又遇到了脚本没有定时触发的问题 我才cron表达式里把每个时间段都加上了 可是都没有定时触发 该怎么解决

额，你好像并没有搞懂什么是cron，请自行百度。

**Comment by jimlee2002** [comment]
No further details provided, this issue would be closed.
