### ISSUE TITLE
多配置文件打卡失败

### ISSUE THREAD

**Issue by leo-buddy** [jimlee2002/Actions-WoZaiXiaoYuanPuncher#30]
在配置USER_01时就遇见这个问题，后隔夜再尝试成功登陆了。在进行USER_02配置时又遇见此问题。environment与secrets配置正确。目前状态为USER_01可以正常打卡，USER_02显示打卡失败，登录信息错误。（严格遵守日志要求修改密码退出再运行脚本）

**Comment by jimlee2002** [comment]
看了下你的日志，USER_02的`USERNAME`是空的，请检查USER_02的`USERNAME`和`PASSWORD`是否正确设置。

**Comment by leo-buddy** [comment]
正确配置的，因账号不能多次进行尝试（会冻结账号）故暂时将USER_2的USERNAME设置为空。

**Comment by jimlee2002** [comment]
请试试填写USER_02中的两个Secrect`USERNAME`和`PASSWORD`，这边看到你配置USER_02后的运行日志（[#15](https://github.com/leo-buddy/Actions-WoZaiXiaoYuanPuncher/actions/runs/1737885568)-[#17](https://github.com/leo-buddy/Actions-WoZaiXiaoYuanPuncher/actions/runs/1737903992)）中，`USERNAME`一直是空的。

**Comment by leo-buddy** [comment]
[已配置并运行，登陆失败

**Comment by jimlee2002** [comment]
> [已配置并运行，登陆失败

![image](https://user-images.githubusercontent.com/21117946/150720245-42df3df7-3380-4b04-9a88-b8847f9de5be.png)
脚本扔未读取到USER_02中的Secrect`USERNAME`。

想请问下你在`WZXY_DailyReport`中设置USER_02的原因是为了给另一个账户打卡吗？

**Comment by leo-buddy** [comment]
对  请问无法读取的问题出在哪里呢（配置USER_01时也出现同样的问题）

**Comment by jimlee2002** [comment]
让我们重新理一遍在日检日报（`WZXY_DailyReport `）中配置USER_02的流程，你可以看看哪里出了问题：
- 你想帮另一个用户打日检日报（`WZXY_DailyReport `），在Actions配置文件`wzxy_dailyreport.yml`中参考注释创建USER_02的配置。
- 在`wzxy_dailyreport.yml`关于USER_02的打卡参数中，你选择`WZXY_CONFIG_02`作为USER_02使用的Environment，**请确保Environment`WZXY_CONFIG_02`并未被其他配置文件或是被脚本健康打卡（`WZXY_HealthCheck `）使用。**
  > ⚠健康打卡（`WZXY_HealthCheck `）的USER_01默认使用Environment`WZXY_CONFIG_02`，请查看`wzxy_healthcheck.yml`
- 假设你还需要使用健康打卡（`WZXY_HealthCheck `），同时Environment`WZXY_CONFIG_02`已经被健康打卡（`WZXY_HealthCheck `）的USER_01所占用，那么在日检日报（`WZXY_DailyReport `）的`wzxy_dailyreport.yml`中，USER_02所使用的Environment就需要改为`WZXY_CONFIG_03`或任何其他未被使用名字。
- 假设在的`wzxy_dailyreport.yml`中，你最终选定`WZXY_CONFIG_03`作为日检日报（`WZXY_DailyReport `）USER_02使用的Environment，那么参照Step2新建Environmen`WZXY_CONFIG_03`并配置相应的Secrect。

**Comment by leo-buddy** [comment]
问题已经解决，将健康打卡（WZXY_HealthCheck）中的环境改为WZXY_CONFIG_03。并重新配置WZXY_CONFIG_02后成功登陆。感谢您的耐心指导。

**Comment by jimlee2002** [comment]
> 问题已经解决，将健康打卡（WZXY_HealthCheck）中的环境改为WZXY_CONFIG_03。并重新配置WZXY_CONFIG_02后成功登陆。感谢您的耐心指导。

不客气。
