### ISSUE TITLE
脚本没有获取到环境中的值

### ISSUE THREAD

**Issue by mujuan12** [jimlee2002/Actions-WoZaiXiaoYuanPuncher#32]
[环境我不知道有没有配置对，在日志里发现那些对应的都没有值
![1645763704(1)](https://user-images.githubusercontent.com/90755758/155654420-de6dd311-421f-4921-b91a-f3286b9e851b.png)
我是这样配置环境的
![1645765910(1)](https://user-images.githubusercontent.com/90755758/155657754-60532844-d155-43f3-a4b5-48cfc2f91729.jpg)

**Comment by jimlee2002** [comment]
![github com](https://user-images.githubusercontent.com/21117946/155682082-e48cd579-8ab6-4b78-adb2-8bcf394194e3.jpeg)

**Comment by mujuan12** [comment]
> ![github com](https://user-images.githubusercontent.com/21117946/155682082-e48cd579-8ab6-4b78-adb2-8bcf394194e3.jpeg)

懂了，我太笨了
