### ISSUE TITLE
没有选健康状况

### ISSUE THREAD

**Issue by mujuan12** [jimlee2002/Actions-WoZaiXiaoYuanPuncher#33]
![1645781634(1)](https://user-images.githubusercontent.com/90755758/155691436-66379640-7340-4d81-869c-2f46dc2ee604.png)
抓包到的数据就是["0"]
![image](https://user-images.githubusercontent.com/90755758/155691559-18160fa0-8a5a-44d6-b451-33dcd7decb47.png)
，环境也没配置错
![image](https://user-images.githubusercontent.com/90755758/155691669-3ea4ee23-708a-4eb8-b26a-27a1800a977d.png)

**Comment by jimlee2002** [comment]
请参考文档设置secrect`ANSWERS`
