### ISSUE TITLE
账号密码错误 报错如下·

### ISSUE THREAD

**Issue by Createrliu** [jimlee2002/Actions-WoZaiXiaoYuanPuncher#34]
Run python wzxy-dailyreport.py
  python wzxy-dailyreport.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/Createrliu/Actions-WoZaiXiaoYuanPuncher/runs/5457851920?check_suite_focus=true#step:6:3).9.10/x6[4](https://github.com/Createrliu/Actions-WoZaiXiaoYuanPuncher/runs/5457851920?check_suite_focus=true#step:6:4)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.10/x[6](https://github.com/Createrliu/Actions-WoZaiXiaoYuanPuncher/runs/5457851920?check_suite_focus=true#step:6:6)4/lib
    DD_BOT_ACCESS_TOKEN: 
    DD_BOT_SECRET: 
    SCT_KEY: 
    BARK_TOKEN: 
    PUSHPLUS_TOKEN: 
    MIAO_CODE: 
    WZXY_USERNAME: 
    WZXY_PASSWORD: 
    WZXY_TEMPERATURE: 
    WZXY_LATITUDE: 
    WZXY_LONGITUDE: 
    WZXY_COUNTRY: 
    WZXY_CITY: 
    WZXY_DISTRICT: 
    WZXY_PROVINCE: 
    WZXY_TOWNSHIP: 
    WZXY_STREET: 
    WZXY_ANSWERS: 
找不到cache文件，正在使用账号信息登录...
{'code': 1, 'message': '请输入用户名和密码'}
登录失败，请检查账号信息
登陆失败，请检查账号信息

**Comment by Createrliu** [comment]
初步判断原因是最新打卡修改密码后不自动退出导致action直接判断登录失败

**Comment by jimlee2002** [comment]
未正确配置secrect，请检查你的配置。
参考https://github.com/jimlee2002/Actions-WoZaiXiaoYuanPuncher/issues/32

**Comment by jimlee2002** [comment]
下个版本会加入检测是否正确配置Secrect。

**Comment by Createrliu** [comment]
配置如下
![image](https://user-images.githubusercontent.com/86226666/157205129-b307c0de-7712-43fc-a5a6-3e82f0a9e40c.png)

**Comment by Createrliu** [comment]
已解决，我修改健康打卡的环境为01后执行打卡会生成同名wxzy01
空文件环境，一直调用的这个空白的，白自己的删了添加到这个生成的里面就好了
