### ISSUE TITLE
日检日报打卡后显示异常

### ISSUE THREAD

**Issue by log1in** [jimlee2002/Actions-WoZaiXiaoYuanPuncher#35]
日检日报打卡脚本返回成功，但是小程序后显示异常
![F0B98DD63BCC0C10B49CE87E72FA38F4](https://user-images.githubusercontent.com/43508732/159404607-ef21df2b-3190-490d-8721-b19e73e39651.jpg)
![Q`Z4%${2LX~37%CP35JF~(F](https://user-images.githubusercontent.com/43508732/159404620-f47fb175-d9da-4bda-a9b9-ebe32be3739a.png)
，

**Comment by log1in** [comment]
> 请参考文档，根据抓包结果配置Secrect`ANSWERS`。

我根据抓包结果设置了Secrect`ANSWERS
![K5NR%@VQ%1JZM~T O6FOPZP](https://user-images.githubusercontent.com/43508732/159498285-9b632992-1159-4a80-a10e-b8a59c687085.png)，
但是发送请求后多选题没有选项被选中。
这里的Secrect`ANSWERS值不就是‘["0"]’吗

**Comment by jimlee2002** [comment]
这边并未在你账号下的公开仓库观察到Action运行日志，方便截图一下Action在`Run Script`一步中的输出吗？包括折叠了的这一行的输出
![image](https://user-images.githubusercontent.com/21117946/159505967-c4665ff3-c3b5-470c-baeb-e16e5b79040d.png)

**Comment by jimlee2002** [comment]
似乎是与 #36 同样的问题，为避免重复，暂时先将本issue关闭。
