### ISSUE TITLE
打卡脚本失效，返回{'code': 7, 'message': '服务异常(7)'}

### ISSUE THREAD

**Issue by SuperCanPlay** [jimlee2002/Actions-WoZaiXiaoYuanPuncher#38]
![image](https://user-images.githubusercontent.com/92358817/163683811-e47d2445-598c-438f-ae81-64ba3390bfab.png)

**Comment by jimlee2002** [comment]
已知错误，有空会尝试debug

**Comment by Alicil** [comment]
![S20417-05254375(1)](https://user-images.githubusercontent.com/100063077/163692234-d2027a76-e01c-4b9a-a4a3-91620c0eea3a.png)
同，出现了上述问题

**Comment by Alicil** [comment]
4月17号，我在校园更新了

**Comment by jimlee2002** [comment]
嗨，感谢反馈，我这边已经复现了同样的问题。
原因是4.17 wzxy 对功能进行了更新。根据[@fukfsa](https://github.com/fukfsa)在https://github.com/jimlee2002/Actions-WoZaiXiaoYuanPuncher/issues/39#issuecomment-1100795164中的截图看，发送的包中加入了新的验证字段，使得已有的所有打卡脚本失效。
由于本人近期工作繁忙，近1个月实在无法抽出时间处理，所以本脚本在一段时间内不会作出修复，非常抱歉！
如果您愿意帮忙解决该问题，欢迎向本仓库发pull request！

**Comment by sizau** [comment]
https://www.sizau.com/a/wzxy-signature.html

SHA256校验

**Comment by Alicil** [comment]
> https://www.sizau.com/a/wzxy-signature.html
> 
> SHA256校验

大佬这个怎么添加

**Comment by BlueSky0329** [comment]
同求操作方法 大佬> https://www.sizau.com/a/wzxy-signature.html
> 
> 
> 
> SHA256校验

**Comment by ziyu-king** [comment]
> 同求操作方法 大佬> https://www.sizau.com/a/wzxy-signature.html
> 
> > SHA256校验

等一个方法

**Comment by LeslieLeung** [comment]
感谢提供链接，正在修复 @sizau

**Comment by LeslieLeung** [comment]
目前打卡问题已经修复，请等待 @jimlee2002 merge。急用可以参考 https://github.com/LeslieLeung/WoZaiXiaoYuanPuncher-Actions

**Comment by hby-gd** [comment]
city_code 应该是 156 + [所在区的身份证前六位]
如 西安市未央区  156610112

**Comment by BlueSky0329** [comment]
> city_code 应该是 156 + [所在区的身份证前六位]
> 
> 如 西安市未央区  156610112

西安citycode 610100

**Comment by jimlee2002** [comment]
> 目前打卡问题已经修复，请等待 @jimlee2002 merge。急用可以参考 https://github.com/LeslieLeung/WoZaiXiaoYuanPuncher-Actions

感谢@sizau 思路与@LeslieLeung 的PR提交，帮大忙了！
@LeslieLeung 的PR我刚才已经初步merge好了，后续的文档今天晚些时候我会进行更新，非常感谢大家帮忙！

**Comment by PandaCZH** [comment]
各位大佬，为什么4.17更新后用Fiddler抓不到我在校园的包了呢？求解

**Comment by jimlee2002** [comment]
文档已进行简要更新。

**Comment by wxm78** [comment]
> 各位大佬，为什么4.17更新后用Fiddler抓不到我在校园的包了呢？ 求解

解决了吗？我最近也出现了同样的问题。
