### ISSUE TITLE
多人打卡，01正常运行，02报错

### ISSUE THREAD

**Issue by SuperCanPlay** [jimlee2002/Actions-WoZaiXiaoYuanPuncher#42]
![FCLJ0@@I {()W%JKVTN2 ~P](https://user-images.githubusercontent.com/92358817/163755948-6b55546e-2544-46f5-86a9-b425a4948fd1.png)
![$7$ T(60JA4L` 71E0F@1T](https://user-images.githubusercontent.com/92358817/163755956-89441abd-3ef0-42de-aa7b-8a156ff948ec.png)

**Comment by LeslieLeung** [comment]
02的环境未设置对应的环境变量

**Comment by SuperCanPlay** [comment]
重新配置了一遍环境变量，出现了不同的问题
![image](https://user-images.githubusercontent.com/92358817/163762067-421bff86-9bd1-45f0-a22d-417cd137e5c4.png)
![image](https://user-images.githubusercontent.com/92358817/163762103-2bd0cb67-e883-46ce-940b-47bf71569ffa.png)

**Comment by SuperCanPlay** [comment]
已经找到问题了：提供的多账户配置实例的代码存在问题
解决办法：将USER_01到run的代码整个复制并修改对应的USER和environment

**Comment by jimlee2002** [comment]
> 已经找到问题了：提供的多账户配置实例的代码存在问题 解决办法：将USER_01到run的代码整个复制并修改对应的USER和environment

fixed
