### ISSUE TITLE
更新抓包教程

### ISSUE THREAD

**Issue by wxm78** [jimlee2002/Actions-WoZaiXiaoYuanPuncher#49]
4.17号我在校园更新后，抓不到我在校园的包了。

**Comment by khaslid** [comment]
试一下在手机上抓，安卓用httpcanary，ios用stream，都是免费的应用。ios的stream刚试过，没问题。

**Comment by wxm78** [comment]
> 试一下在手机上抓，安卓用httpcanary，ios用stream，都是免费的应用。ios的stream刚试过，没问题。

我去试一下，谢谢。

**Comment by Iridescent-9** [comment]
其实可以不用抓包的
![屏幕截图 2022-04-22 115731](https://user-images.githubusercontent.com/61072544/164593490-bedcbd45-7085-4e1d-8c9a-6bbfc97338f9.png)
从第8行可以看见我在校园这东西用的是***腾讯地图***的API
![屏幕截图 2022-04-22 120026](https://user-images.githubusercontent.com/61072544/164594013-b2c802e6-464d-4c76-ae61-7de61536323e.png)
左侧代码216-226行是咱们要在GitHub上配置的东西，右边19-32行是我在校园处理腾讯地图返回的数据并另外起的名字

![屏幕截图 2022-04-22 120501](https://user-images.githubusercontent.com/61072544/164596290-456331fc-c58e-4d3e-890d-61c9370465c1.png)
通过这个图片再看上面我说的就清楚明了了

也就是说你只需要知道你所要定位的经纬度就可以了

**Comment by Alicil** [comment]
> > 其实可以不用抓包的 ![屏幕截图 2022-04-22 115731](https://user-images.githubusercontent.com/61072544/164593490-bedcbd45-7085-4e1d-8c9a-6bbfc97338f9.png) 从第8行可以看见我在校园这东西用的是_**腾讯地图**_的API ![屏幕截图 2022-04-22 120026](https://user-images.githubusercontent.com/61072544/164594013-b2c802e6-464d-4c76-ae61-7de61536323e.png) 左侧代码216-226行是咱们要在GitHub上配置的东西，右边19-32行是我在校园处理腾讯地图返回的数据并另外起的名字
> > ![屏幕截图 2022-04-22 120501](https://user-images.githubusercontent.com/61072544/164596290-456331fc-c58e-4d3e-890d-61c9370465c1.png) 通过这个图片再看上面我说的就清楚明了了
> > 也就是说你只需要知道你所要定位的经纬度就可以了
> 
> 脚本现在的代码太乱了，重构已经提上了日程。 计划中的一个功能就是配置参数时直接输入某个地址/学校名，脚本根据输入的地址信息调用腾讯地图的API查询，并返回相应地理位置数据，保存作为打卡的地理参数。 请拭目以待。

那几个云函数版本里就用的是调用高德的api

**Comment by Iridescent-9** [comment]
它这小程序调用云函数了？那个文件里面啊？

**Comment by Alicil** [comment]
> 它这小程序调用云函数了？那个文件里面啊？

我是说其他几个打卡的项目里，有用到高德逆转地址那个

**Comment by Iridescent-9** [comment]
> > 它这小程序调用云函数了？那个文件里面啊？
> 
> 我是说其他几个打卡的项目里，有用到高德逆转地址那个
> 

噢 那确实是用到高德API了

**Comment by Iridescent-9** [comment]
> 脚本现在的代码太乱了，重构已经提上了日程。
> 计划中的一个功能就是配置参数时直接输入某个地址/学校名，脚本根据输入的地址信息调用腾讯地图的API查询，并返回相应地理位置数据，保存作为打卡的地理参数。
> 请拭目以待。

我正在进行重构，目前正在测试，数日内便会pr

**Comment by Iridescent-9** [comment]
已pr，https://github.com/jimlee2002/Actions-WoZaiXiaoYuanPuncher/pull/65
@jimlee2002

**Comment by jimlee2002** [comment]
> 已pr，https://github.com/jimlee2002/Actions-WoZaiXiaoYuanPuncher/pull/65
> @jimlee2002 
> 
> 

感谢贡献！我最近比较忙，这两天抽空再review一下哈，非常抱歉😥
