### ISSUE TITLE
日检日报打卡失败

### ISSUE THREAD

**Issue by SuperCanPlay** [jimlee2002/Actions-WoZaiXiaoYuanPuncher#57]
![image](https://user-images.githubusercontent.com/92358817/174422790-cb9ac0de-c5fe-4294-9b10-d36c8c1b0a44.png)
![6C3CE0173E2A1F55686CA1D16DF7612E](https://user-images.githubusercontent.com/92358817/174422827-2ef98a13-f636-44c5-b5e8-d77c89eeb5ff.jpg)
从周三下午开始一直出现这个问题，使用常见问题1的方法也没用
![image](https://user-images.githubusercontent.com/92358817/174422890-31e3bce2-c541-435e-8501-ce5e3698cff5.png)

**Comment by j454958047** [comment]
> 
有其他的解决方法吗

**Comment by jimlee2002** [comment]
请尝试 https://github.com/jimlee2002/Actions-WoZaiXiaoYuanPuncher/issues/58#issuecomment-1232292398
