### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by FuDujilm** [jimlee2002/Actions-WoZaiXiaoYuanPuncher#58]
## 无法登录
源码能够正常运行，按照文档中的方法操作后依旧无法登录，输出账号或密码错误（环境中的密码正确）重置密码以后依旧不成功。
![image](https://user-images.githubusercontent.com/72288165/174829899-63090d5d-9b2d-4192-9e69-06247277e029.png)

**Comment by FuDujilm** [comment]
第一天已经封禁24h了，这里是第二天

**Comment by FuDujilm** [comment]
健康打卡

**Comment by B-gor** [comment]
现在也还是这样同样的问题，望解决0.0

**Comment by gz4zzxc** [comment]
尝试使用，简单纯数字/纯英文密码，小程序修改密码后按，清除缓存，退出登陆

**Comment by 1803233552** [comment]
> 尝试使用，简单纯数字/纯英文密码，小程序修改密码后按，清除缓存，退出登陆

感谢，使用这个方法测试成功
