### ISSUE TITLE
定位错误导致提交失败

### ISSUE THREAD

**Issue by superporn** [jimlee2002/Actions-WoZaiXiaoYuanPuncher#60]
data当中的经纬度和街道、乡镇是否要对应，还是必须填写目前所处的位置的定位，我这里返回的信息为：未找到街道信息。
求解决方法，谢谢！！！

**Comment by superporn** [comment]
已解决

**Comment by wxm78** [comment]
> 已解决

有解决方法吗？

**Comment by superporn** [comment]
> 

首先，定位信息与自己当前所在位置无关
其次，定位信息内容 例如：街道信息，城市，乡镇要与代码编号一一对应（代码编号可百度搜索国家乡镇代码）

**Comment by j454958047** [comment]
> > 
> 
> 首先，定位信息与自己当前所在位置无关 其次，定位信息内容 例如：街道信息，城市，乡镇要与代码编号一一对应（代码编号可百度搜索国家乡镇代码）

自己抓的包和网上的代码都试过还是报错

**Comment by Jimmy0346** [comment]
同问，健康打卡没有问题，但是日检日报显示“未获取街道信息”

**Comment by Jimmy0346** [comment]
尝试修改但是依旧报错

**Comment by FuyuZhang** [comment]
已解决，感谢帮助

**Comment by jimlee2002** [comment]
#61
