### ISSUE TITLE
Step3 配置脚本运行时间 描述有误

### ISSUE THREAD

**Issue by 1803233552** [jimlee2002/Actions-WoZaiXiaoYuanPuncher#62]
![image](https://user-images.githubusercontent.com/71918224/188281365-054668b1-969e-48cd-af42-28b9806679c8.png)
![image](https://user-images.githubusercontent.com/71918224/188281378-ff428f5e-8b09-436d-ae36-585d9643ba13.png)
两个默认时间写反了

**Comment by jimlee2002** [comment]
Fixed, Thank you!
