### ISSUE TITLE
使用小程序登录后，在github登录失败

### ISSUE THREAD

**Issue by 1803233552** [jimlee2002/Actions-WoZaiXiaoYuanPuncher#64]
之前是在小程序注销后能成功在github登录，然后有天在小程序登录后，github这里就提示用户名或密码错误
![image](https://user-images.githubusercontent.com/71918224/189531572-97f1c523-3e71-497e-9b2a-b2881c75b8b6.png)

**Comment by jimlee2002** [comment]
是正常现象，在小程序新登陆后有可能会把脚本的登录信息失效掉，唯一的办法是参照文档重新让脚本登陆上

**Comment by 1803233552** [comment]
谢谢大佬，了解了
