### ISSUE TITLE
Project dependencies may have API risk issues

### ISSUE THREAD

**Issue by PyDeps** [jimlee2002/Actions-WoZaiXiaoYuanPuncher#66]
Hi, In **Actions-WoZaiXiaoYuanPuncher**, inappropriate dependency versioning constraints can cause risks.

Below are the dependencies and version constraints that the project is using

```
requests==2.26.0
urllib3==1.26.7
pytz==2021.3
```

The version constraint **==** will introduce the risk of dependency conflicts because the scope of dependencies is too strict.
The version constraint **No Upper Bound** and **\*** will introduce the risk of the missing API Error because the latest version of the dependencies may remove some APIs.

After further analysis, in this project,
The version constraint of dependency **requests** can be changed to *>=0.7.0,<=2.24.0*.
The version constraint of dependency **requests** can be changed to *==2.26.0*.
The version constraint of dependency **pytz** can be changed to *>=2011d,<=2013d*.
The version constraint of dependency **pytz** can be changed to *>=2011b,<=2022.1*.

The above modification suggestions can reduce the dependency conflicts as much as possible, 
and introduce the latest version as much as possible without calling Error in the projects.

The invocation of the current project includes all the following methods.

<details><summary>The calling methods from the requests</summary>
 <pre>requests.get
requests.session
requests.post
</pre>
</details>
<details><summary>The calling methods from the pytz</summary>
 <pre>pytz.timezone
</pre>
</details>
<details><summary>The calling methods from the all methods</summary>
 <pre>WoZaiXiaoYuanPuncher
self.setJwsession
utils.processJson.write
self.getJwsession
hashlib.sha256.string_to_sign_enc.secret_enc.hmac.new.digest
DD_BOT_SECRET.encode
url.format
self.login
round
temperature.split
self.PunchIn
utils.processJson
WoZaiXiaoYuanPuncher.doPunchIn
random.uniform
hmac.new
str
json.dump
requests.session
url.requests.get.json
int
json.load
os.environ.get
self.getResult
msg.json.dumps.encode
headers.data.json.dumps.url.requests.post.json
json.dumps
format.encode
random.seed
open
time.ctime
headers.body.url.requests.post.json
time.time
urllib.parse.quote_plus
base64.b64encode
pytz.timezone
datetime.datetime.now
os.path.exists
float
urllib.parse.urlencode
requests.get
json.loads
pytz.timezone.datetime.datetime.now.strftime
print
WoZaiXiaoYuanPuncher.login
os.mkdir
os.environ.cur_time.os.environ.encode
utils.getRandomTemperature
hashlib.sha256
WoZaiXiaoYuanPuncher.PunchIn
file.close
format
WoZaiXiaoYuanPuncher.sendNotification
utils.getCurrentTime
temperature.find
os.environ.cur_time.os.environ.encode.hashlib.sha256.hexdigest
self.doPunchIn
self.getSeq
self.session.post
requests.post
utils.processJson.read
</pre>
</details>

@developer
Could please help me check this issue?
May I pull a request to fix it?
Thank you very much.

**Comment by jimlee2002** [comment]
This issue seem to be bot-generated, as the range of version you suggest is confusing. 
Closing, Thanks for your help anyway!
